CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE TEACHER (
    ID BIGSERIAL PRIMARY KEY,
    FIRSTNAME VARCHAR(50) NOT NULL,
    LASTNAME VARCHAR(50) NOT NULL,
    AGE INTEGER NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PHONE VARCHAR(20) NOT NULL
);

CREATE TABLE STUDENT (
    ID BIGSERIAL PRIMARY KEY,
    FIRSTNAME VARCHAR(50) NOT NULL,
    LASTNAME VARCHAR(50) NOT NULL,
    AGE INTEGER NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    PHONE VARCHAR(20) NOT NULL
);

CREATE TABLE COURSE (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    TEACHER_ID BIGINT NOT NULL,
    FOREIGN KEY (TEACHER_ID) REFERENCES TEACHER(ID)
);

CREATE TABLE ENROLLMENT (
    COURSE_ID BIGINT NOT NULL,
    STUDENT_ID BIGINT NOT NULL,
    PRIMARY KEY (COURSE_ID, STUDENT_ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSE(ID),
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(ID)
);
